### ISSUE TITLE
Feature Request - Add upcoming Yom Tov candle lighting sensor in Home Assistant

### ISSUE THREAD

**Issue by RebbePod** [py-libhdate/py-libhdate#197]
Not sure where the best place to put this figured it would get lost on the HA forums.

I would like to have a sensor in Home Assistant which gives me the minutes till the next shabbat (shkia) and the minutes go into negative until shabbat is over (upcoming_havdalah but only for shabbat). As well as a second sensor which does the same thing for the minutes until the next holiday.

This is for trying to automate sabbath mode on me GE oven, see more [here](https://github.com/geappliances/home-assistant-adapter/issues/17).

Let me know if there is a better place to put this please.

**Comment by DanBendavid** [comment]
This is already available in HA. 
we should create a ShomerShabat Home Assistant Group

**Comment by tsvi** [comment]
@DanBendavid there's such a WhatsApp group. Feel free to ping me via email/linkedin privately and I'll sent you the link.

@RebbePod unfortunately that's outside the scope of hdate or home assistant. I suppose you can create what you want using a template sensor.
Something as follows should work:

```yaml
template:
  - trigger:
      - trigger: time
        at: sensor.jewish_calendar_upcoming_havdalah
        # This will update every havdalah
    sensor:
      - name: "Upcoming candle lighting from last havdalah"
        state: '{{ (states("sensor.jewish_calendar_upcoming_candle_lighting") }}'
  - sensor:
      - name: "Minutes until shabbes"
        state: "{{ (states("sensor.upcoming_candle_lighting_from_last_havdalah") | as_datetime - now()).total_seconds() // 60 }}"
        unit_of_measurement: "Minutes"
```

Basically, create a timestamp sensor for the upcoming candle lighting that only updates on havdalah.
Then create another sensor that calculates the difference from that original calculation to now.
